### ISSUE TITLE
Possible reuse this app for other projects with data arch?

### ISSUE THREAD

**Issue by johnfelipe** [czammar/arquitectura-datos-proyecto#19]
Hi mate I want to know if is possible modify your app for other propuse for example children food in my country?

**Comment by czammar** [comment]
Hi @johnfelipe; being honest it is quite possible to modify the current development to other context. Please feel free to fork this repo and do the related modifications at your own.

**Comment by johnfelipe** [comment]
Is possible count with your help, of course with your rate...

**Comment by czammar** [comment]
@johnfelipe I appreciate your offer, but I am not interested.
